[package]
name = 'RPesto'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'RPesto'

[dependencies]
extendr-api = '*'
once_cell = "1.21.3"
regex = "1.11.1"
