# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RPesto_wrappers", use_symbols = TRUE, package_name = "RPesto")

#' @usage NULL
#' @useDynLib RPesto, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
print_me_a_tree <- function(s) .Call(wrap__print_me_a_tree, s)

#' @export
extinction_probability <- function(lambda, mu, t, tol) .Call(wrap__extinction_probability, lambda, mu, t, tol)

#' @export
branch_probability <- function(lambda, mu, t, tol) .Call(wrap__branch_probability, lambda, mu, t, tol)

#' @export
likelihood <- function(lambda, mu, phy, tol) .Call(wrap__likelihood, lambda, mu, phy, tol)

#' @export
lognormal_quantile <- function(x, scale, sigma) .Call(wrap__lognormal_quantile, x, scale, sigma)


# nolint end
